version: v1
volumes:
  jupyter-volume:
    name: jupyter-volume
    reference: volume://user/ephemeral
jobs:
  jupyter:
    image:
      uri: docker://quay.io/jupyter/minimal-notebook:latest
    mounts:
      jupyter-volume:
        location: /home/jovyan
    env:
      - HOME=/home/jovyan
    command:
      - /bin/sh
      - "-c"
      - >-
        export NB_USER=$(whoami); test -d $HOME || mkdir $HOME;
        /opt/conda/bin/jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=$JUPYTER_TOKEN --notebook-dir=/home/jovyan
    resource:
      cpu:
        cores: 4
        affinity: NUMA
      memory:
        size: 8GB
      exclusive: true
