version: v1
jobs:
  dmft-triqs-test:
    resource:
      cpu:
        cores: 24
        affinity: NUMA
        threads: false
      memory:
        size: 1GB
        by-core: true
      exclusive: true
    policy:
      timeout:
        execute: 60m
    cwd: /home/triqs
    command:
      - /bin/sh
      - "-c"
      - >-
        python3 -u -m dmft.dmft -b 20 -u 13 -m 8 -n 1 -c 5000 -l 10 -w 200 -a
        "archive_test.h5" -V 1 --bandwidth 26 kagome -t 1 --offset 1 --bins 300
        --nk 2000 |& tee -a "track_test" | tee -a "dmft.log"
    image:
      uri: docker://ghcr.io/saroj-lbl/fuzzball-notes:release
      secret: secret://user/ghcr-lbl
    multinode:
      implementation: openmpi
      nodes: 1
